
package menu;

public class CekBMI extends javax.swing.JFrame {
    double tinggi,berat,ideal;
    
    /**
     * Creates new form CekBMI
     */
    public CekBMI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        ApotekSederhana = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tinggiBadan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        beratBadan = new javax.swing.JTextField();
        bmi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        backMenu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListIndexBMI = new javax.swing.JList<>();
        cek = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cek BMI");
        setMinimumSize(new java.awt.Dimension(500, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setMaximumSize(new java.awt.Dimension(510, 51));
        jPanel2.setMinimumSize(new java.awt.Dimension(510, 51));

        ApotekSederhana.setBackground(new java.awt.Color(102, 153, 255));
        ApotekSederhana.setFont(new java.awt.Font("Kalimati", 1, 24)); // NOI18N
        ApotekSederhana.setForeground(new java.awt.Color(0, 0, 0));
        ApotekSederhana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ApotekSederhana.setText("Cek BMI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ApotekSederhana, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(ApotekSederhana, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel1.setText("Masukkan Usia:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 58, -1, -1));
        getContentPane().add(tinggiBadan, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 143, 414, -1));

        jLabel2.setText("Masukkan Tinggi Badan (cm):");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 120, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 87, 414, -1));

        jLabel3.setText("Masukkan Berat Badan (Kg):");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 176, -1, -1));
        getContentPane().add(beratBadan, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 199, 414, -1));

        bmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmiActionPerformed(evt);
            }
        });
        getContentPane().add(bmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 253, 414, -1));

        jLabel4.setText("BMI:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 230, -1, -1));

        backMenu.setText("Menu");
        backMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenuActionPerformed(evt);
            }
        });
        getContentPane().add(backMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, -1));

        jLabel5.setText("Index BMI :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        ListIndexBMI.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "<18.50  Underweight", "18.50 - 24.99 Normal", ">=25.00 Overweight", ">=30.00 Obesitas" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListIndexBMI);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 240, 40));

        cek.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        cek.setText("Cek");
        cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekActionPerformed(evt);
            }
        });
        getContentPane().add(cek, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmiActionPerformed
        
    }//GEN-LAST:event_bmiActionPerformed

    private void backMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMenuActionPerformed
        ApotekMenu cek = new ApotekMenu();
        cek.setVisible(true);
        dispose();
    }//GEN-LAST:event_backMenuActionPerformed

    private void cekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekActionPerformed
        tinggi = Integer.parseInt(tinggiBadan.getText());
        berat = Integer.parseInt(beratBadan.getText());
        
        ideal = berat / ((tinggi/100)*(tinggi/100));
        bmi.setText(""+Double.toString(ideal));
    }//GEN-LAST:event_cekActionPerformed

    public void bmiCek() {
        new CekBMI().setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApotekSederhana;
    private javax.swing.JList<String> ListIndexBMI;
    private javax.swing.JButton backMenu;
    private javax.swing.JTextField beratBadan;
    private javax.swing.JTextField bmi;
    private javax.swing.JButton cek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField tinggiBadan;
    // End of variables declaration//GEN-END:variables
}
